package com.kunlunsoft.entity;

import java.io.Serializable;

public class User implements Serializable {
    /** */
    private Integer id;

    /** */
    private String name;

    /** */
    private Byte age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.id
     *
     * @return the value of USER.id
     * @mbg.generated Fri Jul 06 13:45:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.id
     *
     * @param id the value for USER.id
     * @mbg.generated Fri Jul 06 13:45:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.name
     *
     * @return the value of USER.name
     * @mbg.generated Fri Jul 06 13:45:15 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.name
     *
     * @param name the value for USER.name
     * @mbg.generated Fri Jul 06 13:45:15 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.age
     *
     * @return the value of USER.age
     * @mbg.generated Fri Jul 06 13:45:15 CST 2018
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.age
     *
     * @param age the value for USER.age
     * @mbg.generated Fri Jul 06 13:45:15 CST 2018
     */
    public void setAge(Byte age) {
        this.age = age;
    }
}